### ISSUE TITLE
Feature request: pin repos to specific versions

### ISSUE THREAD

**Issue by alexmuller** [norm/suited#1]
This is really cool, I like that it might be more lightweight than Puppet/Boxen.

One feature that would help using other people's repos is to be able to pin to a specific version to prevent people from changing things underneath you. For example instead of using:

```
github:norm/suited:setup/password_after_screensaver.sh 
```

I would prefer to say:

```
github:norm/suited@fe24e4335ec1c8f08243b7322e04deebc8c2e3ac:setup/password_after_screensaver.sh 
```

The commit SHA gives me a decent level of confidence that I know what I'm about to run.

**Comment by norm** [comment]
Good suggestion!
